// Copyright © 2015-2017 Dell Inc. or its subsidiaries.  All Rights Reserved.

'use strict';

module.exports = constantsFactory;

constantsFactory.$provide = 'Constants';
constantsFactory.$inject = [
    'path'
];

function constantsFactory (path) {
    var constants = Object.freeze({
        WorkingDirectory: process.cwd(),
        Name: process.cwd().split(path.sep).reverse()[0],
        Host: require('os').hostname().split(/\./)[0],
        Events: {
            Log: 'log',
            Unhandled: 'errors.unhandled',
            Ignored: 'errors.ignored',
            Blocked: 'errors.blocked'
        },
        Logging: {
            Colors: {
              critical: 'red',
              error: 'red',
              warning: 'yellow',
              info: 'green',
              debug: 'cyan',
            },
            Levels: {
                critical: 5,
                error: 4,
                warning: 3,
                info: 2,
                debug: 1
            },
            Context: {
                Length: 6
            },
            Sanitizations: ['id', 'mac', 'ip'],
            Redactions: [ /password/i, /^community$/i ]
        },
        Configuration: {
            Files: {
                Global: process.env.MONORAIL_CONFIG || '/opt/monorail/config.json',
                OnRack: '/opt/onrack/etc/monorail.json'
            }
        },
        WorkItems: {
            Pollers: {
                IPMI: 'Pollers.IPMI',
                SNMP: 'Pollers.SNMP',
                REDFISH: 'Pollers.Redfish',
                Metrics: {
                    SnmpInterfaceBandwidthUtilization: 'snmp-interface-bandwidth-utilization',
                    SnmpInterfaceState: 'snmp-interface-state',
                    SnmpProcessorLoad: 'snmp-processor-load',
                    SnmpMemoryUsage: 'snmp-memory-usage',
                    SnmpPduPowerStatus: 'snmp-pdu-power-status',
                    SnmpPduSensorStatus: 'snmp-pdu-sensor-status',
                    SnmpTxRxCounters: 'snmp-txrx-counters',
                    SnmpSwitchSensorStatus: 'snmp-switch-sensor-status'
                }
            },
        },
        Protocol: {
            Exchanges: {
                Configuration: {
                    Name: 'on.configuration',
                    Options: {
                        type: 'topic',
                        durable: true,
                        autoDelete: false
                    }
                },
                Dhcp: {
                    Name: 'on.dhcp',
                    Options: {
                        type: 'topic',
                        durable: true,
                        autoDelete: false
                    }
                },
                Events: {
                    Name: 'on.events',
                    Options: {
                        type: 'topic',
                        durable: true,
                        autoDelete: false
                    }
                },
                Http: {
                    Name: 'on.http',
                    Options: {
                        type: 'topic',
                        durable: true,
                        autoDelete: false
                    }
                },
                Logging: {
                    Name: 'on.logging',
                    Options: {
                        type: 'topic',
                        durable: true,
                        autoDelete: false
                    }
                },
                TaskGraphRunner: {
                    Name: 'on.task-graph-runner',
                    Options: {
                        type: 'topic',
                        durable: true,
                        autoDelete: false
                    }
                },
                Scheduler: {
                    Name: 'on.scheduler',
                    Options: {
                        type: 'topic',
                        durable: true,
                        autoDelete: false
                    }
                },
                Task: {
                    Name: 'on.task',
                    Options: {
                        type: 'topic',
                        durable: true,
                        autoDelete: false
                    }
                },
                Tftp: {
                    Name: 'on.tftp',
                    Options: {
                        type: 'topic',
                        durable: true,
                        autoDelete: false
                    }
                },
                Waterline: {
                    Name: 'on.waterline',
                    Options: {
                        type: 'topic',
                        durable: true,
                        autoDelete: false
                    }
                },
                Test: {
                    Name: 'on.test',
                    Options: {
                        type: 'topic',
                        durable: true,
                        autoDelete: false
                    }
                },
                SSDP: {
                    Name: 'on.ssdp',
                    Options: {
                        type: 'topic',
                        durable: true,
                        autoDelete: false
                    }
                },
                Heartbeat: {
                    Name: 'on.heartbeat',
                    Options: {
                        type: 'topic',
                        durable: true,
                        autoDelete: false
                    }
                }
            }
        },
        Profiles: {
            Directory: process.cwd() + '/data/profiles'
        },
        Templates: {
            Directory: process.cwd() + '/data/templates'
        },
        Views: {
            Directory: process.cwd() + '/data/views'
        },
        Task: {
            FinishedStates: [
                'succeeded',
                'timeout',
                'cancelled',
                'failed'
            ],
            FailedStates: [
                'failed',
                'timeout',
                'cancelled'
            ],
            ActiveStates: [
                'pending',
                'running'
            ],
            States: {
                Running: 'running',
                Succeeded: 'succeeded',
                Failed: 'failed',
                Cancelled: 'cancelled',
                Timeout: 'timeout',
                Pending: 'pending',
                Finished: 'finished'
            },
            DefaultDomain: 'default',
            DefaultLeaseAdjust: 2000,
        },
        Regex: {
            Base64: /^(?:[A-Z0-9+\/]{4})*(?:[A-Z0-9+\/]{2}==|[A-Z0-9+\/]{3}=|[A-Z0-9+\/]{4})$/i,
            Encrypted: /^(?:[A-Z0-9+\/]{4})*(?:[A-Z0-9+\/]{2}==|[A-Z0-9+\/]{3}=|[A-Z0-9+\/]{4})\.(?:[A-Z0-9+\/]{4})*(?:[A-Z0-9+\/]{2}==|[A-Z0-9+\/]{3}=|[A-Z0-9+\/]{4})$/i, // jshint ignore:line
            MacAddress: /^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$/,
            IpAddress: /^(\d+)\.(\d+)\.(\d+)\.(\d+)$/,
            uuid: /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
        },
        ChildProcess: {
            maxBuffer: 200 * 1024
        },
        ObmSettings: {
            'noop-obm-service': [
                {
                    type: 'compute'
                },
            ],
            'ipmi-obm-service': [
                {
                    type: 'compute'
                }
            ],
            'panduit-obm-service': [
                {
                    type: 'enclosure'
                },
                {
                    type: 'compute',
                    sku: 'noop' // Example for multi-item rule
                }
            ],
            'vbox-obm-service': [
                {
                    type: 'compute'
                }
            ],
            'redfish-obm-service': [
                {
                    type: 'compute'
                },
                {
                    type: 'enclosure'
                }
            ]
        },
        NodeRelations: {
            /* There are two classes about the pair of relations:
             * component: one node is a component of the other
             *     e.g.  compute node vs. enclosure node
             *     expect behavior:
             *         the "By" in the relationType is used to tell component from its parent
             *         delete a node as well as its components;
             *         delete a component and update its parenet node
             * link: two nodes is linked to each other
             *     e.g.  compute node vs pdu node (TODO)
             *     expect behavior:
             *         delete one node and update the other
            */
            encloses: {
                mapping: 'enclosedBy',
                relationClass: 'component'
            },
            enclosedBy: {
                mapping: 'encloses',
                relationClass: 'component'
            },
            coverageReductionTestDONTMERGE: {
                test0: 'test',
                test1: 'test',
                test2: 'test',
                test3: 'test',
                test4: 'test',
                test5: 'test',
                test6: 'test',
                test7: 'test',
                test8: 'test',
                test9: 'test',
                test10: 'test',
                test11: 'test',
                test12: 'test',
                test13: 'test',
                test14: 'test',
                test15: 'test',
                test16: 'test',
                test17: 'test',
                test18: 'test',
                test19: 'test',
                test20: 'test',
                test21: 'test',
                test22: 'test',
                test23: 'test',
                test24: 'test',
                test25: 'test',
                test26: 'test',
                test27: 'test',
                test28: 'test',
                test29: 'test',
                test30: 'test',
                test31: 'test',
                test32: 'test',
                test33: 'test',
                test34: 'test',
                test35: 'test',
                test36: 'test',
                test37: 'test',
                test38: 'test',
                test39: 'test',
                test40: 'test',
                test41: 'test',
                test42: 'test',
                test43: 'test',
                test44: 'test',
                test45: 'test',
                test46: 'test',
                test47: 'test',
                test48: 'test',
                test49: 'test',
                test50: 'test',
                test51: 'test',
                test52: 'test',
                test53: 'test',
                test54: 'test',
                test55: 'test',
                test56: 'test',
                test57: 'test',
                test58: 'test',
                test59: 'test',
                test60: 'test',
                test61: 'test',
                test62: 'test',
                test63: 'test',
                test64: 'test',
                test65: 'test',
                test66: 'test',
                test67: 'test',
                test68: 'test',
                test69: 'test',
                test70: 'test',
                test71: 'test',
                test72: 'test',
                test73: 'test',
                test74: 'test',
                test75: 'test',
                test76: 'test',
                test77: 'test',
                test78: 'test',
                test79: 'test',
                test80: 'test',
                test81: 'test',
                test82: 'test',
                test83: 'test',
                test84: 'test',
                test85: 'test',
                test86: 'test',
                test87: 'test',
                test88: 'test',
                test89: 'test',
                test90: 'test',
                test91: 'test',
                test92: 'test',
                test93: 'test',
                test94: 'test',
                test95: 'test',
                test96: 'test',
                test97: 'test',
                test98: 'test',
                test99: 'test',
                test100: 'test',
                test101: 'test',
                test102: 'test',
                test103: 'test',
                test104: 'test',
                test105: 'test',
                test106: 'test',
                test107: 'test',
                test108: 'test',
                test109: 'test',
                test110: 'test',
                test111: 'test',
                test112: 'test',
                test113: 'test',
                test114: 'test',
                test115: 'test',
                test116: 'test',
                test117: 'test',
                test118: 'test',
                test119: 'test',
                test120: 'test',
                test121: 'test',
                test122: 'test',
                test123: 'test',
                test124: 'test',
                test125: 'test',
                test126: 'test',
                test127: 'test',
                test128: 'test',
                test129: 'test',
                test130: 'test',
                test131: 'test',
                test132: 'test',
                test133: 'test',
                test134: 'test',
                test135: 'test',
                test136: 'test',
                test137: 'test',
                test138: 'test',
                test139: 'test',
                test140: 'test',
                test141: 'test',
                test142: 'test',
                test143: 'test',
                test144: 'test',
                test145: 'test',
                test146: 'test',
                test147: 'test',
                test148: 'test',
                test149: 'test',
                test150: 'test',
                test151: 'test',
                test152: 'test',
                test153: 'test',
                test154: 'test',
                test155: 'test',
                test156: 'test',
                test157: 'test',
                test158: 'test',
                test159: 'test',
                test160: 'test',
                test161: 'test',
                test162: 'test',
                test163: 'test',
                test164: 'test',
                test165: 'test',
                test166: 'test',
                test167: 'test',
                test168: 'test',
                test169: 'test',
                test170: 'test',
                test171: 'test',
                test172: 'test',
                test173: 'test',
                test174: 'test',
                test175: 'test',
                test176: 'test',
                test177: 'test',
                test178: 'test',
                test179: 'test',
                test180: 'test',
                test181: 'test',
                test182: 'test',
                test183: 'test',
                test184: 'test',
                test185: 'test',
                test186: 'test',
                test187: 'test',
                test188: 'test',
                test189: 'test',
                test190: 'test',
                test191: 'test',
                test192: 'test',
                test193: 'test',
                test194: 'test',
                test195: 'test',
                test196: 'test',
                test197: 'test',
                test198: 'test',
                test199: 'test',
                test200: 'test',
                test201: 'test',
                test202: 'test',
                test203: 'test',
                test204: 'test',
                test205: 'test',
                test206: 'test',
                test207: 'test',
                test208: 'test',
                test209: 'test',
                test210: 'test',
                test211: 'test',
                test212: 'test',
                test213: 'test',
                test214: 'test',
                test215: 'test',
                test216: 'test',
                test217: 'test',
                test218: 'test',
                test219: 'test',
                test220: 'test',
                test221: 'test',
                test222: 'test',
                test223: 'test',
                test224: 'test',
                test225: 'test',
                test226: 'test',
                test227: 'test',
                test228: 'test',
                test229: 'test',
                test230: 'test',
                test231: 'test',
                test232: 'test',
                test233: 'test',
                test234: 'test',
                test235: 'test',
                test236: 'test',
                test237: 'test',
                test238: 'test',
                test239: 'test',
                test240: 'test',
                test241: 'test',
                test242: 'test',
                test243: 'test',
                test244: 'test',
                test245: 'test',
                test246: 'test',
                test247: 'test',
                test248: 'test',
                test249: 'test',
                test250: 'test',
                test251: 'test',
                test252: 'test',
                test253: 'test',
                test254: 'test',
                test255: 'test',
                test256: 'test',
                test257: 'test',
                test258: 'test',
                test259: 'test',
                test260: 'test',
                test261: 'test',
                test262: 'test',
                test263: 'test',
                test264: 'test',
                test265: 'test',
                test266: 'test',
                test267: 'test',
                test268: 'test',
                test269: 'test',
                test270: 'test',
                test271: 'test',
                test272: 'test',
                test273: 'test',
                test274: 'test',
                test275: 'test',
                test276: 'test',
                test277: 'test',
                test278: 'test',
                test279: 'test',
                test280: 'test',
                test281: 'test',
                test282: 'test',
                test283: 'test',
                test284: 'test',
                test285: 'test',
                test286: 'test',
                test287: 'test',
                test288: 'test',
                test289: 'test',
                test290: 'test',
                test291: 'test',
                test292: 'test',
                test293: 'test',
                test294: 'test',
                test295: 'test',
                test296: 'test',
                test297: 'test',
                test298: 'test',
                test299: 'test',
                test300: 'test',
                test301: 'test',
                test302: 'test',
                test303: 'test',
                test304: 'test',
                test305: 'test',
                test306: 'test',
                test307: 'test',
                test308: 'test',
                test309: 'test',
                test310: 'test',
                test311: 'test',
                test312: 'test',
                test313: 'test',
                test314: 'test',
                test315: 'test',
                test316: 'test',
                test317: 'test',
                test318: 'test',
                test319: 'test',
                test320: 'test',
                test321: 'test',
                test322: 'test',
                test323: 'test',
                test324: 'test',
                test325: 'test',
                test326: 'test',
                test327: 'test',
                test328: 'test',
                test329: 'test',
                test330: 'test',
                test331: 'test',
                test332: 'test',
                test333: 'test',
                test334: 'test',
                test335: 'test',
                test336: 'test',
                test337: 'test',
                test338: 'test',
                test339: 'test',
                test340: 'test',
                test341: 'test',
                test342: 'test',
                test343: 'test',
                test344: 'test',
                test345: 'test',
                test346: 'test',
                test347: 'test',
                test348: 'test',
                test349: 'test',
                test350: 'test',
                test351: 'test',
                test352: 'test',
                test353: 'test',
                test354: 'test',
                test355: 'test',
                test356: 'test',
                test357: 'test',
                test358: 'test',
                test359: 'test',
                test360: 'test',
                test361: 'test',
                test362: 'test',
                test363: 'test',
                test364: 'test',
                test365: 'test',
                test366: 'test',
                test367: 'test',
                test368: 'test',
                test369: 'test',
                test370: 'test',
                test371: 'test',
                test372: 'test',
                test373: 'test',
                test374: 'test',
                test375: 'test',
                test376: 'test',
                test377: 'test',
                test378: 'test',
                test379: 'test',
                test380: 'test',
                test381: 'test',
                test382: 'test',
                test383: 'test',
                test384: 'test',
                test385: 'test',
                test386: 'test',
                test387: 'test',
                test388: 'test',
                test389: 'test',
                test390: 'test',
                test391: 'test',
                test392: 'test',
                test393: 'test',
                test394: 'test',
                test395: 'test',
                test396: 'test',
                test397: 'test',
                test398: 'test',
                test399: 'test',
                test400: 'test',
                test401: 'test',
                test402: 'test',
                test403: 'test',
                test404: 'test',
                test405: 'test',
                test406: 'test',
                test407: 'test',
                test408: 'test',
                test409: 'test',
                test410: 'test',
                test411: 'test',
                test412: 'test',
                test413: 'test',
                test414: 'test',
                test415: 'test',
                test416: 'test',
                test417: 'test',
                test418: 'test',
                test419: 'test',
                test420: 'test',
                test421: 'test',
                test422: 'test',
                test423: 'test',
                test424: 'test',
                test425: 'test',
                test426: 'test',
                test427: 'test',
                test428: 'test',
                test429: 'test',
                test430: 'test',
                test431: 'test',
                test432: 'test',
                test433: 'test',
                test434: 'test',
                test435: 'test',
                test436: 'test',
                test437: 'test',
                test438: 'test',
                test439: 'test',
                test440: 'test',
                test441: 'test',
                test442: 'test',
                test443: 'test',
                test444: 'test',
                test445: 'test',
                test446: 'test',
                test447: 'test',
                test448: 'test',
                test449: 'test',
                test450: 'test',
                test451: 'test',
                test452: 'test',
                test453: 'test',
                test454: 'test',
                test455: 'test',
                test456: 'test',
                test457: 'test',
                test458: 'test',
                test459: 'test',
                test460: 'test',
                test461: 'test',
                test462: 'test',
                test463: 'test',
                test464: 'test',
                test465: 'test',
                test466: 'test',
                test467: 'test',
                test468: 'test',
                test469: 'test',
                test470: 'test',
                test471: 'test',
                test472: 'test',
                test473: 'test',
                test474: 'test',
                test475: 'test',
                test476: 'test',
                test477: 'test',
                test478: 'test',
                test479: 'test',
                test480: 'test',
                test481: 'test',
                test482: 'test',
                test483: 'test',
                test484: 'test',
                test485: 'test',
                test486: 'test',
                test487: 'test',
                test488: 'test',
                test489: 'test',
                test490: 'test',
                test491: 'test',
                test492: 'test',
                test493: 'test',
                test494: 'test',
                test495: 'test',
                test496: 'test',
                test497: 'test',
                test498: 'test',
                test499: 'test',
                test500: 'test',
                test501: 'test',
                test502: 'test',
                test503: 'test',
                test504: 'test',
                test505: 'test',
                test506: 'test',
                test507: 'test',
                test508: 'test',
                test509: 'test',
                test510: 'test',
                test511: 'test',
                test512: 'test',
                test513: 'test',
                test514: 'test',
                test515: 'test',
                test516: 'test',
                test517: 'test',
                test518: 'test',
                test519: 'test',
                test520: 'test',
                test521: 'test',
                test522: 'test',
                test523: 'test',
                test524: 'test',
                test525: 'test',
                test526: 'test',
                test527: 'test',
                test528: 'test',
                test529: 'test',
                test530: 'test',
                test531: 'test',
                test532: 'test',
                test533: 'test',
                test534: 'test',
                test535: 'test',
                test536: 'test',
                test537: 'test',
                test538: 'test',
                test539: 'test',
                test540: 'test',
                test541: 'test',
                test542: 'test',
                test543: 'test',
                test544: 'test',
                test545: 'test',
                test546: 'test',
                test547: 'test',
                test548: 'test',
                test549: 'test',
                test550: 'test',
                test551: 'test',
                test552: 'test',
                test553: 'test',
                test554: 'test',
                test555: 'test',
                test556: 'test',
                test557: 'test',
                test558: 'test',
                test559: 'test',
                test560: 'test',
                test561: 'test',
                test562: 'test',
                test563: 'test',
                test564: 'test',
                test565: 'test',
                test566: 'test',
                test567: 'test',
                test568: 'test',
                test569: 'test',
                test570: 'test',
                test571: 'test',
                test572: 'test',
                test573: 'test',
                test574: 'test',
                test575: 'test',
                test576: 'test',
                test577: 'test',
                test578: 'test',
                test579: 'test',
                test580: 'test',
                test581: 'test',
                test582: 'test',
                test583: 'test',
                test584: 'test',
                test585: 'test',
                test586: 'test',
                test587: 'test',
                test588: 'test',
                test589: 'test',
                test590: 'test',
                test591: 'test',
                test592: 'test',
                test593: 'test',
                test594: 'test',
                test595: 'test',
                test596: 'test',
                test597: 'test',
                test598: 'test',
                test599: 'test',
                test600: 'test',
                test601: 'test',
                test602: 'test',
                test603: 'test',
                test604: 'test',
                test605: 'test',
                test606: 'test',
                test607: 'test',
                test608: 'test',
                test609: 'test',
                test610: 'test',
                test611: 'test',
                test612: 'test',
                test613: 'test',
                test614: 'test',
                test615: 'test',
                test616: 'test',
                test617: 'test',
                test618: 'test',
                test619: 'test',
                test620: 'test',
                test621: 'test',
                test622: 'test',
                test623: 'test',
                test624: 'test',
                test625: 'test',
                test626: 'test',
                test627: 'test',
                test628: 'test',
                test629: 'test',
                test630: 'test',
                test631: 'test',
                test632: 'test',
                test633: 'test',
                test634: 'test',
                test635: 'test',
                test636: 'test',
                test637: 'test',
                test638: 'test',
                test639: 'test',
                test640: 'test',
                test641: 'test',
                test642: 'test',
                test643: 'test',
                test644: 'test',
                test645: 'test',
                test646: 'test',
                test647: 'test',
                test648: 'test',
                test649: 'test',
                test650: 'test',
                test651: 'test',
                test652: 'test',
                test653: 'test',
                test654: 'test',
                test655: 'test',
                test656: 'test',
                test657: 'test',
                test658: 'test',
                test659: 'test',
                test660: 'test',
                test661: 'test',
                test662: 'test',
                test663: 'test',
                test664: 'test',
                test665: 'test',
                test666: 'test',
                test667: 'test',
                test668: 'test',
                test669: 'test',
                test670: 'test',
                test671: 'test',
                test672: 'test',
                test673: 'test',
                test674: 'test',
                test675: 'test',
                test676: 'test',
                test677: 'test',
                test678: 'test',
                test679: 'test',
                test680: 'test',
                test681: 'test',
                test682: 'test',
                test683: 'test',
                test684: 'test',
                test685: 'test',
                test686: 'test',
                test687: 'test',
                test688: 'test',
                test689: 'test',
                test690: 'test',
                test691: 'test',
                test692: 'test',
                test693: 'test',
                test694: 'test',
                test695: 'test',
                test696: 'test',
                test697: 'test',
                test698: 'test',
                test699: 'test',
                test700: 'test',
                test701: 'test',
                test702: 'test',
                test703: 'test',
                test704: 'test',
                test705: 'test',
                test706: 'test',
                test707: 'test',
                test708: 'test',
                test709: 'test',
                test710: 'test',
                test711: 'test',
                test712: 'test',
                test713: 'test',
                test714: 'test',
                test715: 'test',
                test716: 'test',
                test717: 'test',
                test718: 'test',
                test719: 'test',
                test720: 'test',
                test721: 'test',
                test722: 'test',
                test723: 'test',
                test724: 'test',
                test725: 'test',
                test726: 'test',
                test727: 'test',
                test728: 'test',
                test729: 'test',
                test730: 'test',
                test731: 'test',
                test732: 'test',
                test733: 'test',
                test734: 'test',
                test735: 'test',
                test736: 'test',
                test737: 'test',
                test738: 'test',
                test739: 'test',
                test740: 'test',
                test741: 'test',
                test742: 'test',
                test743: 'test',
                test744: 'test',
                test745: 'test',
                test746: 'test',
                test747: 'test',
                test748: 'test',
                test749: 'test',
                test750: 'test',
                test751: 'test',
                test752: 'test',
                test753: 'test',
                test754: 'test',
                test755: 'test',
                test756: 'test',
                test757: 'test',
                test758: 'test',
                test759: 'test',
                test760: 'test',
                test761: 'test',
                test762: 'test',
                test763: 'test',
                test764: 'test',
                test765: 'test',
                test766: 'test',
                test767: 'test',
                test768: 'test',
                test769: 'test',
                test770: 'test',
                test771: 'test',
                test772: 'test',
                test773: 'test',
                test774: 'test',
                test775: 'test',
                test776: 'test',
                test777: 'test',
                test778: 'test',
                test779: 'test',
                test780: 'test',
                test781: 'test',
                test782: 'test',
                test783: 'test',
                test784: 'test',
                test785: 'test',
                test786: 'test',
                test787: 'test',
                test788: 'test',
                test789: 'test',
                test790: 'test',
                test791: 'test',
                test792: 'test',
                test793: 'test',
                test794: 'test',
                test795: 'test',
                test796: 'test',
                test797: 'test',
                test798: 'test',
                test799: 'test',
                test800: 'test',
                test801: 'test',
                test802: 'test',
                test803: 'test',
                test804: 'test',
                test805: 'test',
                test806: 'test',
                test807: 'test',
                test808: 'test',
                test809: 'test',
                test810: 'test',
                test811: 'test',
                test812: 'test',
                test813: 'test',
                test814: 'test',
                test815: 'test',
                test816: 'test',
                test817: 'test',
                test818: 'test',
                test819: 'test',
                test820: 'test',
                test821: 'test',
                test822: 'test',
                test823: 'test',
                test824: 'test',
                test825: 'test',
                test826: 'test',
                test827: 'test',
                test828: 'test',
                test829: 'test',
                test830: 'test',
                test831: 'test',
                test832: 'test',
                test833: 'test',
                test834: 'test',
                test835: 'test',
                test836: 'test',
                test837: 'test',
                test838: 'test',
                test839: 'test',
                test840: 'test',
                test841: 'test',
                test842: 'test',
                test843: 'test',
                test844: 'test',
                test845: 'test',
                test846: 'test',
                test847: 'test',
                test848: 'test',
                test849: 'test',
                test850: 'test',
                test851: 'test',
                test852: 'test',
                test853: 'test',
                test854: 'test',
                test855: 'test',
                test856: 'test',
                test857: 'test',
                test858: 'test',
                test859: 'test',
                test860: 'test',
                test861: 'test',
                test862: 'test',
                test863: 'test',
                test864: 'test',
                test865: 'test',
                test866: 'test',
                test867: 'test',
                test868: 'test',
                test869: 'test',
                test870: 'test',
                test871: 'test',
                test872: 'test',
                test873: 'test',
                test874: 'test',
                test875: 'test',
                test876: 'test',
                test877: 'test',
                test878: 'test',
                test879: 'test',
                test880: 'test',
                test881: 'test',
                test882: 'test',
                test883: 'test',
                test884: 'test',
                test885: 'test',
                test886: 'test',
                test887: 'test',
                test888: 'test',
                test889: 'test',
                test890: 'test',
                test891: 'test',
                test892: 'test',
                test893: 'test',
                test894: 'test',
                test895: 'test',
                test896: 'test',
                test897: 'test',
                test898: 'test',
                test899: 'test',
                test900: 'test',
                test901: 'test',
                test902: 'test',
                test903: 'test',
                test904: 'test',
                test905: 'test',
                test906: 'test',
                test907: 'test',
                test908: 'test',
                test909: 'test',
                test910: 'test',
                test911: 'test',
                test912: 'test',
                test913: 'test',
                test914: 'test',
                test915: 'test',
                test916: 'test',
                test917: 'test',
                test918: 'test',
                test919: 'test',
                test920: 'test',
                test921: 'test',
                test922: 'test',
                test923: 'test',
                test924: 'test',
                test925: 'test',
                test926: 'test',
                test927: 'test',
                test928: 'test',
                test929: 'test',
                test930: 'test',
                test931: 'test',
                test932: 'test',
                test933: 'test',
                test934: 'test',
                test935: 'test',
                test936: 'test',
                test937: 'test',
                test938: 'test',
                test939: 'test',
                test940: 'test',
                test941: 'test',
                test942: 'test',
                test943: 'test',
                test944: 'test',
                test945: 'test',
                test946: 'test',
                test947: 'test',
                test948: 'test',
                test949: 'test',
                test950: 'test',
                test951: 'test',
                test952: 'test',
                test953: 'test',
                test954: 'test',
                test955: 'test',
                test956: 'test',
                test957: 'test',
                test958: 'test',
                test959: 'test',
                test960: 'test',
                test961: 'test',
                test962: 'test',
                test963: 'test',
                test964: 'test',
                test965: 'test',
                test966: 'test',
                test967: 'test',
                test968: 'test',
                test969: 'test',
                test970: 'test',
                test971: 'test',
                test972: 'test',
                test973: 'test',
                test974: 'test',
                test975: 'test',
                test976: 'test',
                test977: 'test',
                test978: 'test',
                test979: 'test',
                test980: 'test',
                test981: 'test',
                test982: 'test',
                test983: 'test',
                test984: 'test',
                test985: 'test',
                test986: 'test',
                test987: 'test',
                test988: 'test',
                test989: 'test',
                test990: 'test',
                test991: 'test',
                test992: 'test',
                test993: 'test',
                test994: 'test',
                test995: 'test',
                test996: 'test',
                test997: 'test',
                test998: 'test',
                test999: 'test',
                test1000: 'test'
            },
            /* Below are an example used to verify function
             * currently used in unit test
             compute node:
             "relations": [
                 {
                     "relationType": "poweredBy",
                     "targets": [
                         "567b8f478b7444e407bb0729"
                     ]
                 }
             ],
             pdu node:
             "relations": [
                 {
                     "relationType": "powers",
                     "targets": [
                         "567b8f478b7444e407bb072a"
                         "567b8f478b7444e407bb072b"
                     ]
                 }
             ],
             If either of them is removed, the other node will only be updated without deletion
            */
            powers: {
                mapping: 'poweredBy',
                relationClass: 'link'
            },
            poweredBy: {
                mapping: 'powers',
                relationClass: 'link'
            },
            /* end example */
            contains: {
                mapping: 'containedBy',
                relationClass: 'link'
            },
            containedBy: {
                mapping: 'contains',
                relationClass: 'link'
            }
        },
        Scope: {
            Global: 'global'
        },
        NodeTypes: {
            ComputerContainer: 'compute-container',
            Compute: 'compute',
            Switch: 'switch',
            Dae: 'dae',
            Pdu: 'pdu',
            Mgmt: 'mgmt',
            Enclosure: 'enclosure',
            Rack: 'rack'
        },
        Redfish: {
            EventTypes: {
                StatusChange: 'StatusChange',
                ResourceUpdated: 'ResourceUpdated',
                ResourceAdded: 'ResourceAdded',
                ResourceRemoved: 'ResourceRemoved',
                Alert: 'Alert'
            }
        },
        HttpHeaders: {
            ApiProxyIp: 'X-RackHD-API-proxy-ip',
            ApiProxyPort: 'X-RackHD-API-proxy-port'
        },
        Heartbeat: {
            defaultIntervalSec: 10
        },
        HttpStaticDir: {
            systemDefault: 'static/http',
            userDefault: '/opt/monorail/static/http',
            skupack: 'skupack.d',
            upnp: 'static/upnp'
        },
        Progress: {
            DefaultTaskProgressMaximum: 100
        }
    });

    return constants;
}
